module.exports = {
  total_logs: 0,
  min_temperature: Number.POSITIVE_INFINITY,
  max_temperature: Number.NEGATIVE_INFINITY,
  mean_temperature: 0,
  min_humidity: Number.POSITIVE_INFINITY,
  max_humidity: Number.NEGATIVE_INFINITY,
  mean_humidity: 0,
  min_heat_index: Number.POSITIVE_INFINITY,
  max_heat_index: Number.NEGATIVE_INFINITY,
  mean_heat_index: 0,
  min_vpd: Number.POSITIVE_INFINITY,
  max_vpd: Number.NEGATIVE_INFINITY,
  mean_vpd: 0,
}